# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('code_oag', models.CharField(blank=True, db_column='Code_oag', max_length=20, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, db_column='Zip_code', max_length=35, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=4, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=20, null=True)),
                ('operation_time', models.CharField(blank=True, db_column='Operation_Time', max_length=50, null=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
            ],
        ),
    ]
