# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, db_column=b'City', max_length=100, null=True)),
                ('code_oag', models.CharField(blank=True, db_column=b'Code_oag', max_length=20, null=True)),
                ('description', models.CharField(blank=True, db_column=b'Description', max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, db_column=b'Zip_code', max_length=35, null=True)),
                ('country', models.CharField(blank=True, db_column=b'Country', max_length=4, null=True)),
                ('latitude', models.CharField(blank=True, db_column=b'Latitude', max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, db_column=b'Longitude', max_length=20, null=True)),
                ('operation_time', models.CharField(blank=True, db_column=b'Operation_Time', max_length=50, null=True)),
                ('code', models.CharField(blank=True, db_column=b'Code', max_length=20, null=True)),
            ],
        ),
    ]
